language: node_js
node_js:
  - 10.15.3
cache: npm

install:
  - npm install

script:
  - npm run check:markdown
  - npm run build

deploy:
  provider: script
  script: npm run zeit-deploy
  skip_cleanup: true
  on:
    all_branches: true
